Flutter iOS support
google/cronet.dart pull request #32
Opened 2021-10-25 15:23 UTC by zhileichen

This PR intends to add iOS support for flutter

2021-11-09 03:11 UTC, unsuitable001 approved these changes
Thank you so much @zhileichen for this valuable PR. LGTM.

Related #5 

cc @dcharkes

2021-11-15 09:24 UTC, dcharkes commented
@unsuitable001 It looks like the formatter isn't happy on the CI. Also on files which aren't touched by this PR. Could you take a look to get the CI happy before merging this PR?

2021-11-15 09:56 UTC, dcharkes approved these changes
lgtm when CI is green.

Thanks @zhileichen !

2021-11-15 10:08 UTC, unsuitable001 requested changes
Also, in https://github.com/zhileichen/cronet.dart/blob/baeab391e8c3059bd4a24bcf8cc9d5e89d782a1e/lib/src/exceptions.dart#L21

Change it to:

```dart
    final b = StringBuffer()
      ..write('HttpException: ')
      ..write(message);
```

These 2 changes should be enough to make the analyser happy :)

2021-11-15 10:08 UTC, unsuitable001 commented on lib/src/constants.dart
> +  else if (!(Platform.isLinux ||
Change it to
```dart
  } else if (!(Platform.isLinux ||
      platform.startsWith('linux') ||
```

2021-11-15 15:47 UTC, merged

2021-11-15 15:49 UTC, dcharkes commented
I just noticed that we didn't bump the version to 0.0.7 and added no entry in the changelog.md Without a version bump I cannot publish a new version of the package on pub.dev. Would you mind making a PR to bump the version and update the changelog?